---
title: ""
---

- C.S. Reddy, A. Manonmani, M. Babu and R. Sowdhamini(2006).Enhanced structure prediction of gene products containing class III adenylate cyclases. The Fourth Asia Pacific Bioinformatics  Conference (APBC 2006). 13-16 February 2006, Taipei, Taiwan.

- C.S. Reddy, A. Manonmani, M. Babu and R. Sowdhamini(2006).Enhanced structure prediction of gene products containing class III adenylate cyclases. The Indo-French Bioinformatics Meeting (IFBM 2006), 12-14 June 2006, Bangalore, India.

- Chandra Sekhar Reddy Chilamakuri, Boris Lenhard (2011), Epigenetic features of genomic regulatory blocks. International conference on Omics Meets Disease (15-18 Dec 2011), Kolkata, India.

- Chandra Sekhar Reddy Chilamakuri, Boris Lenhard. Chromatin state dynamics in genomic regulatory blocks across six human cell lines. ISMB, 15-17 July2012, Long Beach, California, USA.

- C.S.R Chilamakuri et al. Performance Comparison of four exome capturing systems for next-generation sequencing . EACR Special Conference on Cancer Genomics,25–28 June 2013, Cambridge, UK.
