---
title: ""
---

* I enjoy listening to audiobooks, especially in the genres of science, ancient history, Biographies and recent political history.

  * Some of my Favorite audible boooks
    * Biographies:
      * [Azaad: An Autobiography By Ghulam Nabi Azad](https://amzn.eu/d/31Q0GVJ)
      * [Portraits of Power: Half a Century of Being at Ringside By N.K.Singh](https://amzn.eu/d/21uT7gS)
      * [Elon Musk By Walter Isaacson](https://amzn.eu/d/cefXPsp)

    * Political stories:
      * [1991: How P. V. Narasimha Rao Made History By Sanjaya Baru](https://amzn.eu/d/3g5Mkqe)

    * History related books:
      * [The Golden Road: How Ancient India Transformed the World By William Dalrymple ](https://amzn.eu/d/bxRbnDM)
      * [The Making of the Modern Middle East: A Personal History By  Jeremy Bowen](https://amzn.eu/d/6h4cm1G)
      * [శతాబ్దాల తెలుగు పత్రికలు - తీరు తెన్నులు - Kiran PrabhaTalk Show](https://youtu.be/PhZ9473PBBQ?list=PLlGz0Ss-PpNoqzta0uH1CiFzFCQ764oic)

    * Related to death and philosophy:
      * [Regrets of the Dying: Stories and Wisdom That Remind Us How to Live By Georgina Scull ](https://amzn.eu/d/8yEFK5g)



* I also enjoy watching documentaries related to science and ancient history.
  * Some of my favorite documentaries include:
    * Ancient History:
      * [Hindu Nectar: Spiritual Wanderings in India](https://youtu.be/zLvr80ZrCqo?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)
      * [History of Yoga ](https://youtu.be/JoRwXMLsVis?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)
      * [XUAN ZANG](https://youtu.be/ulDzLjz0wdw?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)

    * Science documentaries:
      * [Order And Disorder](https://youtu.be/aeaQpuYPsy8)
      * [Uranium: Twisting the Dragon's Tail](https://www.amazon.co.uk/gp/video/detail/B0CVNHHN55/ref=atv_dp_share_cu_r)


