---
title: "Chandra Chilamakuri"
author: NULL
date: "2025-06-02"
output: 
  rmdformats::material:
    css: fix-references.css 
    
bibliography: Chandra_citations.bib
csl: vancouver-year-sorted.csl
nocite: "@*"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = F)
```



# Who am I?

I am a Senior Computational Biologist at University of Cambridge with several years of research and teaching experience, holding a PhD in Bioinformatics. My work has focused on applying computational approaches to solve complex biological problems, and I have a strong foundation in biology, statistics, and computing. In addition to my research, I’ve enjoyed teaching students at various levels, and I’m passionate about making science accessible and engaging for learners of all backgrounds.


# Digital Profiles

- [University of Cambridge](https://bioinfotraining.bio.cam.ac.uk/staff/chandra-chilamakuri)
- [Google Scholar](https://scholar.google.com/citations?user=GljD3GEAAAAJ&hl=en)
- [Linkedin](https://www.linkedin.com/in/chandrachilamakuri/)
- [CRUKCI](https://www.cruk.cam.ac.uk/core-facilities/bioinformatics/)




# Contact

📲 +44 77 58 512 560

📧 chandu.ncbs@gmail.com

# Hobbies

* **Audible Books**: I enjoy listening to audiobooks, especially in the genres of science, ancient history, Biographies and recent political history. 

  * Some of my Favorite audible boooks
    * Biographies: 
      * [Azaad: An Autobiography By Ghulam Nabi Azad](https://amzn.eu/d/31Q0GVJ)
      * [Portraits of Power: Half a Century of Being at Ringside By N.K.Singh](https://amzn.eu/d/21uT7gS)
      * [Elon Musk By Walter Isaacson](https://amzn.eu/d/cefXPsp)
  
    * Political stories:
      * [1991: How P. V. Narasimha Rao Made History By Sanjaya Baru](https://amzn.eu/d/3g5Mkqe)
  
    * History related books:
      * [The Golden Road: How Ancient India Transformed the World By William Dalrymple ](https://amzn.eu/d/bxRbnDM)
      * [The Making of the Modern Middle East: A Personal History By  Jeremy Bowen](https://amzn.eu/d/6h4cm1G)
      * [శతాబ్దాల తెలుగు పత్రికలు - తీరు తెన్నులు - Kiran PrabhaTalk Show](https://youtu.be/PhZ9473PBBQ?list=PLlGz0Ss-PpNoqzta0uH1CiFzFCQ764oic)
    
    * Related to death and philosophy:
      * [Regrets of the Dying: Stories and Wisdom That Remind Us How to Live By Georgina Scull ](https://amzn.eu/d/8yEFK5g)
  
    

* I also enjoy watching documentaries related to science and ancient history.
  * Some of my favorite documentaries include:
    * Ancient History:
      * [Hindu Nectar: Spiritual Wanderings in India](https://youtu.be/zLvr80ZrCqo?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)
      * [History of Yoga ](https://youtu.be/JoRwXMLsVis?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)
      * [XUAN ZANG](https://youtu.be/ulDzLjz0wdw?list=PLtQf1vOY-CmlmDps3xYrk-AEd5YwQQwV2)
      
    * Science documentaries:
      * [Order And Disorder](https://youtu.be/aeaQpuYPsy8)
      * [Uranium: Twisting the Dragon's Tail](https://www.amazon.co.uk/gp/video/detail/B0CVNHHN55/ref=atv_dp_share_cu_r)
      



# CV


## Experience

* **Jan 2016-Present**: Senior Computational Biologist, [CRUK Cambridge Institute](https://www.cruk.cam.ac.uk/), University of Cambridge, UK.
  - Providing computational expertise to the design and analysis of research projects.
  - Leading the development of computational methods for analyzing high-throughput sequencing and proteomics data.
  - Develop and deliver training courses in statistics and computational biology.

* **Apr 2015-Dec 2015**: Computational Biologist, [CRUK Cambridge Institute](https://www.cruk.cam.ac.uk/), University of Cambridge, UK.
  - Providing computational expertise to the design and analysis of research projects.
  - Developed computational methods for analyzing high-throughput sequencing data.
  - Collaborated with experimental biologists to design and analyze experiments.

* **Sept 2012-Jan 2015**: Computational Biologist, [Oslo University Hospital](https://www.ous-research.no/), Norway.
  - Worked on the [Norwegian Personalized Cancer Medicine project](https://www.nature.com/articles/nature.2012.9949), My work involved in analysis and interpretation of high-throughput sequencing data from cancer patients.
  - I was involved in the development and delivery of next-generation sequencing data analysis courses for researchers and clinicians.

* **Sept 2010-Aug 2012**: Postdoctoral Researcher, [University of Bergen](https://www.uib.no/), Norway.
  - Worked on the [NEUROXSYS](https://cordis.europa.eu/project/id/223262/reporting/it). Involved in the analysis and interpretation of high-throughput sequencing data from patients with neurological disorders.

* **Nov 2009-Aug 2010**: Postdoctoral Researcher, [NCBS](https://www.ncbs.res.in/), Bangalore India.
  - Involved in the modeling of Myosin protein tails for understanding the molecular mechanisms and functional diversity of Myosin proteins.
  
  
## Education

* **2004-2009**: PhD in Computational Biology, [NCBS](https://www.ncbs.res.in/), [Tata Institute of Fundamental Research](https://www.tifr.res.in/), India.
* **2007-2009**: PhD in Computational Biology, [Université de La Réunion](https://www.univ-reunion.fr), La Réunion, France.
* **2001-2002**: Master’s in Plant Physiology, [Bidhan Chandra Krishi Viswavidyalaya](https://www.bckv.edu.in/), West Bengal, India.
* **1996-2001**: Bachelor’s in Agricultural sciences,[Acharya N G Ranga Agricultural University](https://angrau.ac.in/), India.

## Teaching

* **Introduction to Statistical Analysis.**
  * Oct 2021, CRUKCI, University of Cambridge, UK.
  * Nov 2022, CRUKCI, University of Cambridge, UK.
  * Nov 2023, CRUKCI, University of Cambridge, UK.
  * Oct 2024, CRUKCI, University of Cambridge, UK.

* **Linear Modelling with R**
  * Jan 2022, University of Cambridge, UK.
  * Feb 2023, University of Cambridge, UK.

* **Linear modeling: Hands-on with Fixed and Mixed effects models**
  * Feb 2023, CRUKCI, University of Cambridge, UK.
  * Feb 2024, CRUKCI, University of Cambridge, UK.

* **An Introduction to Machine Learning**
  * July 2021, University of Cambridge, UK.
  * Sept 2023, University of Cambridge, UK.
  * July 2023, University of Cambridge, UK.
  * July 2024, University of Cambridge, UK.

* **UKHSA-WHO: SARS-CoV-2 Bioinformatics Workshop**
  * Jan 2023, Abu Dhabi, UAE.
  * May 2023, Accra, Ghana.
  * Feb 2024, Panama City, Panama.
  
* **Principles of Experimental Designs**
  * Nov 2015, CRUKCI, University of Cambridge,UK.
  * Nov 2016, CRUKCI, University of Cambridge,UK.
  * Nov 2017, CRUKCI, University of Cambridge,UK.
  * Nov 2018, CRUKCI, University of Cambridge,UK.
  * Oct 2019, CRUKCI, University of Cambridge,UK.
  * Jan 2021, CRUKCI, University of Cambridge,UK.
  * Oct 2021, CRUKCI, University of Cambridge,UK.
  * Oct 2022, CRUKCI, University of Cambridge,UK.
  * Oct 2023, CRUKCI, University of Cambridge,UK.
  * Oct 2024, CRUKCI, University of Cambridge, UK.

* **Reproducible Research in R**
  * Dec 2022, University of Cambridge, UK.
  * Feb 2023, University of Cambridge, UK.
  * Jan 2025, Sanger Institute, Cambridge, UK.

* **Data Science in Python**
  * Apr 2019, University of Cambridge, UK.
  * Apr 2020, University of Cambridge, UK.
  * Mar 2021, University of Cambridge, UK.
  * Nov 2022, University of Cambridge, UK.

* **CRUK Cambridge Center Bioinformatics Summer School**
  * July 2017, University of Cambridge, UK.
  * July 2018, University of Cambridge, UK.
  * July 2019, University of Cambridge, UK.

* **Winter School: Bioinformatics Data Exploration for Biologists**
  * Dec 2020, University of Cambridge, UK.

* **High Performance Computing: An Introduction**
  * Apr 2022, University of Cambridge, UK.
  * July 2022, University of Cambridge, UK.
  * Oct 2023, University of Cambridge, UK.
  * Oct 2024, University of Cambridge, UK.
  
* **Introduction High Throughput Sequencing**
  * Oct 2013, University of Oslo, Norway.
  * Oct 2014, University of Oslo, Norway.

* **Analysis of high-throughput sequencing data with Bioconductor**
  * May 2015, University of Cambridge, UK.
  * Mar 2015, University of Cambridge, UK.
  * Mar 2018, University of Cambridge, UK.
  * Dec 2018, University of Cambridge, UK.

* **Analysis of bulk RNA-seq data**
  * Mar 2015, SVIMS bioinformatics center, Tirupati, India.
  * Jan 2017,CDFD, Hyderabad, India.
  * July 2020, University of Cambridge, UK.
  * June 2021, University of Cambridge, UK.
  * July 2021, University of Cambridge, UK.
  * Nov 2021, University of Cambridge, UK.
  * Apr 2022, University of Cambridge, UK.
  * Nov 2022, University of Cambridge, UK.
  * June 2023, University of Cambridge, UK.
  * Sept 2023, University of Cambridge, UK.
  * Mar 2024, University of Cambridge, UK.
  * Nov 2024, University of Cambridge, UK.
  
* **Analysis of single cell RNA-seq data.**
  * Nov 2021, University of Cambridge, UK.
  * Mar 2022, CRUKCI, University of Cambridge, UK.
  * Apr 2022, University of Cambridge, UK.
  * June 2022, University of Cambridge, UK.
  * Sept 2022, University of Cambridge, UK.
  * Jan 2023, University of Cambridge, UK.
  * Sept 2023, University of Cambridge, UK.
  * Mar 2022, CRUKCI, University of Cambridge, UK.
  * May 2024, University of Cambridge, UK.
  * Dec 2024, University of Cambridge, UK.
  * Feb 2025, University of Cambridge, UK.

* **An Introduction to Solving Biological Problems with R**
  * June 2016, University of Cambridge, UK.
  * Dec 2016, S.V. Agricultural College, India.
  * June 2017, University of Cambridge, UK.
  * Dec 2018, University of Cambridge, UK.
  * Mar 2020, University of Cambridge, UK.
  * Nov 2021, University of Cambridge, UK.
  * Apr 2022, APBioNET, Perdana University, Malaysia.

* **An Introduction to Solving Biological Problems with Python**
  * July 2020, University of Cambridge, UK.
  * June 2021, University of Cambridge, UK.
  * Sept 2021, University of Cambridge, UK.
  * Sept 2023, University of Cambridge, UK.
  * Jan 2024, Sanger Institute, UK.
  * Oct 2024, University of Cambridge, UK.

* **Data Manipulation and Visualization using R**
  * Feb 2019, University of Cambridge, UK.

* **NST Part II BBS Bioinformatics**
  * Jan 2021, University of Cambridge, UK.

* **Introduction to Command Line Linux**
  * Mar 2021, University of Cambridge, UK.

* **Bitesize R**:
  * Apr 2019, CRUKCI, University of Cambridge, UK.
  * Apr 2023, CRUKCI, University of Cambridge, UK.


## Honors and Awards

- Conseil Régional de La Réunion fellowship for pursuing Ph.D for the year 2006 - 2009
- Junior research fellowship for the year 2004 to 2006 to work in welcome trust project.
- CSIR-UGC Junior Research Fellowship, December 2003.
- Junior Research Fellowship, July 2001. Secured 18th rank in Indian council for   Agricultural Research exam. A national wide exam for granting fellowships for pursuing M.Sc.
- Visiting Professor Dec 2023, University of Horticultural Sciences, Bagalkot, Karnataka, India.

## Conferences

- C.S. Reddy, A. Manonmani, M. Babu and R. Sowdhamini(2006).Enhanced structure prediction of gene products containing class III adenylate cyclases. The Fourth Asia Pacific Bioinformatics  Conference (APBC 2006). 13-16 February 2006, Taipei, Taiwan.

- C.S. Reddy, A. Manonmani, M. Babu and R. Sowdhamini(2006).Enhanced structure prediction of gene products containing class III adenylate cyclases. The Indo-French Bioinformatics Meeting (IFBM 2006), 12-14 June 2006, Bangalore, India.

- Chandra Sekhar Reddy Chilamakuri, Boris Lenhard (2011), Epigenetic features of genomic regulatory blocks. International conference on Omics Meets Disease (15-18 Dec 2011), Kolkata, India.

- Chandra Sekhar Reddy Chilamakuri, Boris Lenhard. Chromatin state dynamics in genomic regulatory blocks across six human cell lines. ISMB, 15-17 July2012, Long Beach, California, USA.

- C.S.R Chilamakuri et al. Performance Comparison of four exome capturing systems for next-generation sequencing . EACR Special Conference on Cancer Genomics,25–28 June 2013, Cambridge, UK.

## Invited talks

- Enhanced structure prediction of gene products containing class III adenylate cyclases. The Indo-French Bioinformatics Meeting (IFBM 2006), 12-14 June 2006, Bangalore, India.
- Bioinformatics as a career. 13 Oct 2009, Agricultural College, Mahanandi, India.
- Orientation of transmembrane peptides under hydrophobic mismatch condition. 26 Apr 2010, Max Planck Institute for Evolutionary Anthropology, Leipzig, Germany.
- Orientation of transmembrane peptides under hydrophobic mismatch condition. 29 Apr 2010, The Computational Biology Unit, University of Bergen, Norway.
- Performance Comparison of four exome capturing systems for next-generation sequencing. The Norwegian Genomics Consortium meeting 3-4 Apr 2013, Oslo.
- Importance of Genomic Medicine: Tale of a Liposarcoma Patient. 26 August 2014, The Jackson Laboratory for Genomic Medicine, Farmington, Connecticut, USA.
- Importance of Genomic Medicine: Tale of a Liposarcoma Patient. 15 January 2015, IIIT Hyderabad, India.
- Importance of Genomic Medicine: Tale of a Liposarcoma Patient. 16 December 2016, SVIMS Bioinformatics Center, Tirupati, India.
- Careers in Bioinformatics, 7 Mar 2018, The Leys School, Cambridge, UK.
- Careers in Bioinformatics, 9 Mar 2019, The Leys School, Cambridge, UK.
- Careers in Bioinformatics, 7 Mar 2020, The Leys School, Cambridge, UK.
- Big Data and Biology. 23 Jan 2024, GITAM University, Bangalore, India.



## Publications

